version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
  build:
    commands:
      - npm ci
      - docker build -t node-encrypt:1 .
      - docker tag node-encrypt:1 $DOCKER_HUB_USERNAME/node-encrypt:1
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $DOCKER_HUB_USERNAME/node-encrypt:1
